#!/bin/bash

cd "$(dirname "$0")"

die() {
    echo "$@"
    exit 1 
}

setup() {
    echo "Prepare the Host Envrionment with necessary download (once)"
    sudo apt install tmux 
}

run() {
    echo Launch the frontend and backend server in two panel
    test -x /usr/bin/tmux || die "do './dev setup' first to install the environment'"
    tmux split && tmux send-keys "npx quasar dev"
    tmux split && tmux send-keys 'find . -name "api/" | entr -c cargo run'
}

"$@"
